### ISSUE TITLE
How did this work?

### ISSUE THREAD

**Issue by rlingineni** [hczhcz/makeohio#1]
I'm trying to interface with an airbar - and I'm wondering how you guys were able to decode the data? 

Also - did this work on a Mac by any chance. Did this read the USB data directly?

**Comment by hczhcz** [comment]
We just read the USB HID data from `/dev/hidraw*`.
See [fetch_notes_airbar.cpp](https://github.com/hczhcz/airbar-makeohio/blob/master/fetch_notes_airbar.cpp) for reference.
